; PlatformIO Project Configuration File
; Unified AVRboy Environment (16MHz External Crystal)

[env:ATmega328P]
platform = atmelavr
board = ATmega328P
board_build.f_cpu = 16000000L

; Unified ISP Upload via USBasp
upload_protocol = usbasp
upload_flags =
    -e
    -Ulfuse:w:0xFF:m
    -Uhfuse:w:0xD9:m
    -Uefuse:w:0xFD:m

monitor_speed = 9600

build_flags = 
    -D DEBUG
    -fno-lto
    -Wl,--section-start=.system_api=0x3F00
    -Wl,--section-start=.bootloader=0x7000
    -Wl,--section-start=.data=0x800140
    -Wl,--undefined=jump_to_app
    -Wl,--undefined=bootloader_main
